# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('short_code', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, choices=[('a', 'Approved'), ('n', 'Not Approved')], default='n', max_length=1)),
                ('default_commission_per_share', models.DecimalField(decimal_places=4, default=0.03, max_digits=4)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('u', 'Undefined')], default='u', max_length=1)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('symbol', models.CharField(max_length=10)),
                ('cusip', models.CharField(blank=True, max_length=10, null=True)),
                ('stop_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('limit_price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cusip',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='transaction',
            name='executed_price',
            field=models.DecimalField(decimal_places=4, default=0.034, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='execution_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='filled_quantity',
            field=models.DecimalField(decimal_places=4, default=123, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
